name: webpack ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x  

    - name: Install dependencies and build
      run: |
        npm install webpack webpack-cli babel-loader @babel/core @babel/preset-env @babel/plugin-transform-runtime
        npm install terser-webpack-plugin        
        npx webpack-cli --mode production
        rm -rf node_modules 

    - name: Move build to prod/
      run: |
        rm -rf prod  
        mv dist prod  

    - name: Commit and push changes to the prod folder
      run: |

        # Stage the build output for commit
        git add prod/ package.json package-lock.json

        # Commit the changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Bundle via Webpack"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
