name: Webpack and GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

permissions:
  contents: write  # Ensure write access to the repository content

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x  # Specify Node.js version

    - name: Install dependencies and build
      run: |
        npm install webpack webpack-cli --save-dev
        npm install raw-loader --save-dev
        npx webpack-cli  # Run webpack build

    - name: Move build to docs/
      run: |
        rm -rf docs  # Clear existing docs folder
        mv dist docs  # Move the build to docs folder

    - name: Commit and push changes to the docs folder
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/
        git commit -m "Update GitHub Pages build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
