name: Bundle and Release Russo.js

on:
  push:
    branches:
      - master  # Trigger the action on every push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger for PRs targeting the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js with PNPM
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use the Node.js version you prefer
          registry-url: 'https://registry.npmjs.org' # Use the default NPM registry
      
      - name: Install PNPM
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install # Install dependencies using PNPM
      
      - name: Install Webpack and Bundling Tools
        run: |
          pnpm add -D webpack webpack-cli babel-loader @babel/core @babel/preset-env terser-webpack-plugin # Install Webpack, Babel, and required plugins

      - name: Create Webpack Configuration
        run: |
          echo "const path = require('path');" > webpack.config.cjs
          echo "module.exports = {" >> webpack.config.cjs
          echo "  mode: 'production'," >> webpack.config.cjs
          echo "  entry: './index.js'," >> webpack.config.cjs
          echo "  output: {" >> webpack.config.js
          echo "    path: path.resolve(__dirname, 'dist')," >> webpack.config.cjs
          echo "    filename: 'index.bundle.js'," >> webpack.config.cjs
          echo "    library: 'Russo'," >> webpack.config.cjs
          echo "    libraryTarget: 'umd'," >> webpack.config.cjs
          echo "  }," >> webpack.config.cjs
          echo "  module: {" >> webpack.config.cjs
          echo "    rules: [" >> webpack.config.cjs
          echo "      {" >> webpack.config.cjs
          echo "        test: /\.js$/," >> webpack.config.cjs
          echo "        exclude: /node_modules/," >> webpack.config.cjs
          echo "        use: {" >> webpack.config.js
          echo "          loader: 'babel-loader'," >> webpack.config.cjs
          echo "          options: {" >> webpack.config.cjs
          echo "            presets: ['@babel/preset-env']" >> webpack.config.cjs
          echo "          }," >> webpack.config.cjs
          echo "        }," >> webpack.config.cjs
          echo "      }," >> webpack.config.cjs
          echo "    ]," >> webpack.config.cjs
          echo "  }," >> webpack.config.cjs
          echo "  optimization: {" >> webpack.config.cjs
          echo "    minimize: true," >> webpack.config.cjs
          echo "  }," >> webpack.config.cjs
          echo "};" >> webpack.config.cjs
          
      - name: Build with Webpack
        run: npx webpack --config webpack.config.cjs # Use Webpack to bundle your files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/index.bundle.js # Path to the bundled file created by Webpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
